### ISSUE TITLE
Add Inventory

### ISSUE THREAD

**Issue by Sahithi142** [ramyagovind13/shop-easy#10]
Goal:
As an Admin, I want to add new products to my inventory so that I can keep track of them.

Acceptance Criteria:
•	An interface should be available in the system for adding new items.
•	Interface should include a field for all relevant product information, such as Product name, category, description, measure, etc.
•	The system should validate the input data to ensure it is comprehensive as well as precise.
•	The system should save the new product information to the database after a successful validation.
•	A confirmation message stating that the product has been added successfully should be displayed by the system.
•	The inventory listing needs to show the recently added item.

**Comment by chethana613** [comment]
Implementation completed, tested.

**Comment by chethana613** [comment]
Implementation completed, tested.
