### ISSUE TITLE
Student login authentication backend implementation

### ISSUE THREAD

**Issue by mounikonduru** [ramyagovind13/shop-easy#3]
Goal : 
            As a student, I want a secure login system for accessing my student account, so I can view my items and other Information.

Acceptance criteria: 

1. I should be able to enter credentials and submit the form.
2. The system should validate my credentials and grant access only if they are correct.
3. After a successful login, I should be directed to their account.
4. I should have the option to log out from my account to ensure the security of my data.
5. The system should provide a password reset option in case I forget my password.

**Comment by chethana613** [comment]
Implementation Completed
