### ISSUE TITLE
View available inventory

### ISSUE THREAD

**Issue by chethana613** [ramyagovind13/shop-easy#4]
### **Goal:** 
`As a student user of Shop Easy, I should be able to view the available inventory in the Shop Easy so that I can order items of my Interest`

### **Acceptance Criteria:**

- Upon accessing "View Available Inventory," it should display a list of food items available in the Shop Easy pantry.
- Each item in the inventory list should include product code, name, product category, quantity available, and expiration date.
- The inventory list should be updated in real-time based on the admin updates and maintain accuracy.
- Student should be able to view more details about an item by clicking on it, including a description and calories.

**Comment by ramyagovind13** [comment]
Completely implemented GET for viewing the available product details.
