### ISSUE TITLE
Order placement

### ISSUE THREAD

**Issue by ramyagovind13** [ramyagovind13/shop-easy#7]
``` As a student who is using the pantry platform ,I want to place orders from the selected items from the pantry inventory so that I can conveniently get the items from the pantry. ```

#### Acceptance criteria
1. Pantry platform should allow Students to view and select items from the inventory.
2. Before placing order, students should able to review the selected items in the cart.
3. After reviewing the cart, Students should able to place orders.

**Comment by chethana613** [comment]
Implemented, tested and integrated with UI. hence closing.
