### ISSUE TITLE
Cancel Order

### ISSUE THREAD

**Issue by adarsh302** [ramyagovind13/shop-easy#9]
**Story**

As a student, I want to be able to cancel an order at any circumstances, even after the order is placed, so that I have the flexibility to adjust my orders to accommodate changes in any  situations.

**Acceptance criteria** 

-  The Student should be to log in with his credentials.

-  Upon successful login, the Student should be able to access his inventory.

-  In the inventory , there should be able to "View Order History."

-  When selecting "View Order History," the Student should be able to see the  list of their past orders.

-  There should be a "Cancel" button. which  will cancels the previous order that was placed.

The Student will  receive a confirmation message upon successful  cancellation of the order.

**Comment by chethana613** [comment]
Implemented, tested and integrated with UI. Hence closing
